Ext.define('PET.view.ChangeWithdrawalDayVW', {
	id:"ChangeWithdrawalDayVW",
    extend: 'Ext.Panel',
		alias: 'widget.ChangeWithdrawalDayVW',
    config: {
      fullscreen: true,
			layout:'fit',
 	   items: 
			[
				{
					xtype:'toolbar',
					title:'Change Billing Day',
					docked:'top',
					items:
					[
					{
						ui:'plain',
						iconMask:true,
						xtype:'button',
						iconCls:'reply',
						go:'right_PolicyVW'
					}
					]
				
				},
				{
					xtype:'formpanel',
					items:[
					{
						xtype:'selectfield',
						label:'Billing Day:',
						options:[
						{
							text:'1',value:'1'
						},
						{
							text:'2',value:'2'
						},
						{
							text:'1',value:'1'
						},
						{
							text:'2',value:'2'
						},
						{
							text:'3',value:'3'
						},
						{
							text:'4',value:'4'
						},
						{
							text:'5',value:'5'
						},
						{
							text:'6',value:'6'
						},
						{
							text:'7',value:'7'
						},
						{
							text:'8',value:'8'
						},
						{
							text:'9',value:'9'
						},
						{
							text:'10',value:'10'
						},
						{
							text:'11',value:'11'
						},
						{
							text:'12',value:'12'
						},
						{
							text:'13',value:'13'
						},
						{
							text:'14',value:'14'
						},
						{
							text:'15',value:'15'
						},
						{
							text:'16',value:'16'
						},
						{
							text:'17',value:'17'
						},
						{
							text:'18',value:'18'
						},
						{
							text:'19',value:'19'
						},
						{
							text:'20',value:'20'
						},
						{
							text:'21',value:'21'
						},
						{
							text:'22',value:'22'
						},
						{
							text:'23',value:'23'
						},
						{
							text:'24',value:'24'
						},
						{
							text:'25',value:'25'
						},
						{
							text:'26',value:'26'
						},
						{
							text:'27',value:'27'
						},
						{
							text:'28',value:'28'
						}
						]
					}
					
					]
				},
				{
					xtype:'toolbar',
					docked:'bottom',
					items:[
					{
						xtype:'button',
						docked:'right',
						text:'Save'
					}
					]
				}
			]		
   }
});